# Generated by Django 6.0.6 on 2026-08-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id_document',
            field=models.FileField(blank=True, null=True, upload_to='student_ids/'),
        ),
    ]
