# Generated by Django 6.0.5 on 2026-06-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentposition',
            name='duration_weeks',
        ),
        migrations.AddField(
            model_name='attachmentposition',
            name='duration',
            field=models.CharField(default='TBD', max_length=100),
        ),
        migrations.AddField(
            model_name='attachmentposition',
            name='slots',
            field=models.IntegerField(default=1),
        ),
    ]
